stages:
  - test

.install_deps: &install_system_deps
  before_script:
    - >
      dnf install -y --refresh
      python3 python3-devel make gcc which xz libxml2-devel
      libxslt-devel enchant python3-tox

flake:
  stage: test
  image: fedora:latest
  <<: *install_system_deps
  script:
    - dnf install -y --refresh ShellCheck
    - export TOXENV=check
    - tox "-n $(nproc)"

pytest:
  stage: test
  image: fedora:latest
  <<: *install_system_deps
  script:
    - >
      dnf install -y --refresh
      xorriso genisoimage python36 python34 python2
      python2-devel python2-pip
    - export LANG=C.UTF-8
    # Python 2.7
    - export PYTHON=python2.7
    - pip install tox
    - export TOXENV=unit_py2_7
    - tox "-n $(nproc)"
    # Python 3.4
    - export TOXENV=unit_py3_4
    - export PYTHON=python3.4
    - tox "-n $(nproc)"
    # Python 3.6
    - export TOXENV=unit_py3_6
    - export PYTHON=python3.6
    - tox "-n $(nproc)"
    # Python 3.7
    - export TOXENV=unit_py3_7
    - export PYTHON=python3.7
    - tox "-n $(nproc)"

doc:
  stage: test
  image: fedora:latest
  <<: *install_system_deps
  script:
    - >
      dnf install -y --refresh
      latexmk texlive-cmap texlive-metafont texlive-ec texlive-babel-english
      texlive-fncychap texlive-fancyhdr texlive-titlesec texlive-tabulary
      texlive-framed texlive-wrapfig texlive-parskip texlive-upquote
      texlive-capt-of texlive-needspace texlive-makeindex texlive-times
      texlive-helvetic texlive-courier texlive-gsftopk texlive-updmap-map
      texlive-dvips
    - export TOXENV=doc
    - tox "-n $(nproc)"
